
// In the Module.h, in a EditorModule - Ie MyProjectEditor.h

private:
    void PrepareAutoGeneratedDefaultEvents();

#define RegisterDefaultEvent(Class, FuncName) \
    (FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, Class::StaticClass(), GET_FUNCTION_NAME_CHECKED(Class, FuncName)))


// In the CPP, StartupModule:
PrepareAutoGeneratedDefaultEvents();

void FPathfinderEditorModule::PrepareAutoGeneratedDefaultEvents()
{
	//RegisterDefaultEvent(AUserToolBase, ReceiveBeginPlay);
	RegisterDefaultEvent(AUserToolBase, ReceiveTick);
	RegisterDefaultEvent(AUserToolBase, OnEquipped);
	RegisterDefaultEvent(AUserToolBase, OnUnequipped);
	RegisterDefaultEvent(AUserToolBase, StartPrimaryInteraction);
	RegisterDefaultEvent(AUserToolBase, StopPrimaryInteraction);

	RegisterDefaultEvent(AUserToolBase, StartAltAction1);
	RegisterDefaultEvent(AUserToolBase, StopAltAction1);

	RegisterDefaultEvent(AUserToolBase, StartAltAction2);
	RegisterDefaultEvent(AUserToolBase, StopAltAction2);
}

// The above functions are BlueprintNative Functions, IE:
	UFUNCTION(BlueprintNativeEvent)
	void OnEquipped(AVRHandBase* GrabbingHand);